package downloaders.courses_set_downloaders.instruction_downloader

import downloaders.course_downloaders.instruction_downloader.IDownloaderByInstruction
import entity.Course

interface ICoursesSetByInstructionDownloader : IDownloaderByInstruction<Course>